Bump min iOS to 12 - required to build with Xcode 14.3
`/Skia-m110-ad42464-1-iosSim-Release-arm64/src/core/SkTLazy.h:87:24: error: 'value' is unavailable: introduced in iOS 12.0`

See https://github.com/JetBrains/skiko/pull/702